chatgpt:
  proxy-host: 127.0.0.1
  proxy-port: 10809
  model: text-davinci-003 #可选
  chat-model: gpt-3.5-turbo #可选 模型
  retries: 10 #重新请求次数可选，默认为5
  session-expiration-time: 10 #可选，不填则会话永不过期
  token: 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
spring:
  web:
    resources:
      static-locations: classpath:/static/, classpath:/templates/
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    cache: false #页面修改后，关闭缓存，立刻书信
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: src/main
      exclude: static/**,templates/** #设置不需要重启的目录
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.221:3306/GPTApi?useSSL=false
    username: root
    password: 123456
server:
  port: 8080

