
chatgpt:
  proxy-host: 127.0.0.1
  proxy-port: 10809
  model: text-davinci-003 #可选
  chat-model: gpt-3.5-turbo #可选 模型
  retries: 10 #重新请求次数可选，默认为5
  session-expiration-time: 10 #可选，不填则会话永不过期
  token: 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
spring:
  web:
    resources:
      static-locations: classpath:/static/, classpath:/templates/
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    cache: false #页面修改后，关闭缓存，立刻书信
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: src/main
      exclude: static/**,templates/** #设置不需要重启的目录
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.221:3306/GPTApi?useSSL=false
    username: root
    password: 123456
      #redis
  redis:
    host: 192.168.3.221
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 6000
        max-idle: 5
        min-idle: 1
      # 哨兵配置
      #sentinel:
      #  master: mymaster
      #  nodes: 192.168.2.9:6379,192.168.2.10:6379
server:
  port: 8080

ximo:
  mqtt:
    host: tcp://192.168.3.221:1883
    #MQTT-连接服务器默认客户端ID
    clientid: mqttjs_6589ad2cec
    #MQTT-用户名
    username: admin
    #MQTT-密码
    password: public
    #连接超时
    timeout: 1000
    #心跳检查时间
    keepalive: 10
